name: Swift

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  lint:
      name: Run Swiftlint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: SwiftLint
          run: make lint
