name: Swift

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  lint:
      name: SwiftLint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Lint
          run: make lint-ci
